version: '3'

services:
    
  web:
    build: ./web
    ports:
      - 8000:8000
 
      
    

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
  
 

      
      
    



    